### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ITAYC0HEN**
This Pull Request is fixing a small typo in the README file. It also makes sure that the line numbers are incrementing.

### CODE REVIEW

**Comment by davidt99** [comment]
Hi @ITAYC0HEN, thanks for the contribution! 
The numbering was on purpose so when adding new items in the middle, we won't need to go over the next items and change them.
Now I realize is not that user friendly for a reader outside of github.

**Comment by davidt99** [comment]
Can you fix the typo in the previous word as well :wink: ?

**Comment by ITAYC0HEN** [comment]
_(Added more changes)_

@davidt99, yes indeed :) It is too dependent on your Markdown viewer and it looks weird on some viewers. Since the effort of tweaking some numbers isn't that scary, I think it will look better like this.

What do you think?

**Comment by ITAYC0HEN** [comment]
Sorry for the mess, it was a bug on Github that prevent the PR from fetching new commits. Should be good now for a sqaush and merge

**Comment by davidt99** [comment]
Thanks!

**Pull request merged**
